In [3]:
from sklearn.datasets import make_circles
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

In [4]:
## Generation of points
X, y = make_circles(n_samples=1000, noise=0.11, factor=0.4)

In [13]:
X

array([[-0.41549695, -0.25678361],
       [-0.43034211,  0.94723704],
       [ 0.34590045, -0.49715372],
       ...,
       [-0.35528596,  0.90473098],
       [ 0.97495386, -0.06273215],
       [ 0.33116786,  0.36802453]])

In [14]:
X.shape

(1000, 2)

In [15]:
y

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,

In [16]:
y.shape

(1000,)

In [5]:
## Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [6]:
## Definition of the classifier
svc = LinearSVC()

In [7]:
## Let's train the model 
svc.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [8]:
## Prediction on the test data
y_pred = svc.predict(X_test)

In [9]:
## Let's calculate the accuracy of the model 
accuracy_1 = accuracy_score(y_test, y_pred)
accuracy_1

0.616

### Now let's apply a transformation on the data to make it easy for our linear classifier

In [10]:
## Definition of a function phi ==> for the transformation 
def phi(x1, x2):
    return np.array([x1, x2, x1**2 + x2**2])

In [11]:
## Generation of new datasets
new_X = np.array([phi(x1, x2) for x1, x2 in zip(X[:,0], X[:,1])])

In [12]:
new_X

array([[-0.41549695, -0.25678361,  0.23857554],
       [-0.43034211,  0.94723704,  1.08245234],
       [ 0.34590045, -0.49715372,  0.36680894],
       ...,
       [-0.35528596,  0.90473098,  0.94476625],
       [ 0.97495386, -0.06273215,  0.95447034],
       [ 0.33116786,  0.36802453,  0.2451142 ]])

In [17]:
## Split the dataset
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(new_X, y)

In [18]:
## definition of the classifier
svc = LinearSVC()

In [19]:
## Training
svc.fit(X_train_2, y_train_2)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [20]:
## Prediction on the test dataset
y_pred_2 = svc.predict(X_test_2)

In [21]:
## Accuracy of the new model
accuracy_2 = accuracy_score(y_test_2, y_pred_2)
accuracy_2

0.996

## Now we can see clearly that the same model is now able to classifier correctly the new data because its space makes it easy.  Nevertheless in this case, we have use a transformation function that we know, that would not be the same everytime. Hence the concept of "kernel trick". We have some kernels as:
- polynomial kernel
- sigmoid kernel 
- Radial Basis Function (RBF)

In [22]:
from sklearn.svm import SVC

In [23]:
## Let's create a model with "RBF" as kernel
model = SVC(kernel="rbf")

In [25]:
## Fitting the data
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
## Prediction 
y_pred_3 = model.predict(X_test)

In [27]:
## Accuracy
accuracy_3 = accuracy_score(y_test, y_pred_3)
accuracy_3

1.0

### Wow!!! we get here an accuracy of 100%. That is awesome.